### ISSUE TITLE
Controller crash due out of sync PathIndex

### ISSUE THREAD

**Issue by bithavoc** [haproxytech/kubernetes-ingress#115]
I downloaded a vanilla community yaml from the website and installed it in k3s:

The controller stays in crash loop, the logs report the following stack trace:

```
2019/11/16 08:24:31 controller.go:100: Starting HAProxy with /etc/haproxy/haproxy.cfg
2019/11/16 08:24:31 controller.go:119: Running on haproxy-ingress-8589cc68c7-8bvjj
[WARNING] 319/082431 (18) : Can't open server state file '/var/state/haproxy/global': No such file or directory
2019/11/16 08:24:31 controller.go:72: Running on Kubernetes version: v1.14.3-k3s.1 linux/amd64
[NOTICE] 319/082431 (23) : New worker #1 (24) forked
panic: runtime error: index out of range [5] with length 1

goroutine 70 [running]:
main.(*HAProxyController).updateHAProxy(0xc00000b680, 0x0, 0x0)
        /src/controller-haproxy.go:85 +0x2428
main.(*HAProxyController).SyncData(0xc00000b680, 0xc0003da3c0, 0xc00009c120)
        /src/controller-monitor.go:120 +0x519
created by main.(*HAProxyController).monitorChanges
        /src/controller-monitor.go:26 +0xb9
```

**Comment by Mo3m3n** [comment]
Hi I think this bug is already fixed in the dev branch, can you please try the image with the dev tag ?
Tomorrow we will issue a new release including bug fixes in the dev branch.

**Comment by bithavoc** [comment]
Ahh, I've been trying the master branch and adding some logging in an attempt to figure out whats going on. Trying dev branch now.

**Comment by bithavoc** [comment]
Thganks, crash definitely fixed in `dev` branch, the problem seems to be something else now. closing.
