### ISSUE TITLE
panic: runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by ohardy** [haproxytech/kubernetes-ingress#159]
Full log of the pod:

```
2020/02/26 18:27:43 HAProxy Ingress Controller v1.3.2 8fed7bc

2020/02/26 18:27:43 Build from: git@github.com:haproxytech/kubernetes-ingress.git
2020/02/26 18:27:43 Build date: 2020-02-12T15:23:39

2020/02/26 18:27:43 ConfigMap: default/haproxy-configmap
2020/02/26 18:27:43 Ingress class: haproxy
2020/02/26 18:27:43 Publish service: 
2020/02/26 18:27:43 main.go:99: Default backend service: haproxy-controller/ingress-default-backend
2020/02/26 18:27:43 main.go:100: Default ssl certificate: /
2020/02/26 18:27:43 controller.go:97: Running with  HA-Proxy version 2.0.11 2019/12/11 - https://haproxy.org/
2020/02/26 18:27:43 controller.go:102: Starting HAProxy with /etc/haproxy/haproxy.cfg
2020/02/26 18:27:43 controller.go:115: Running on haproxy-ingress-6666c899b6-wft58
2020/02/26 18:27:43 controller.go:69: Running on Kubernetes version: v1.16.5-gke.2 linux/amd64
[WARNING] 056/182743 (19) : Can't open server state file '/var/state/haproxy/global': No such file or directory
[NOTICE] 056/182743 (20) : New worker #1 (21) forked
2020/02/26 18:27:48 controller.go:369: Confiugring default_backend ingress-default-backend from ingress DefaultService
panic: runtime error: index out of range [-1]

goroutine 23 [running]:
main.(*HAProxyController).writeCert(0xc00000be00, 0xc0000889c0, 0x5a, 0x1eb5110, 0x0, 0x0, 0x1eb5110, 0x0, 0x0, 0x0, ...)
        /src/controller-https.go:60 +0xa77
main.(*HAProxyController).handleSecret(0xc00000be00, 0xc0004ffc00, 0x12, 0xc0004ffbe0, 0x1a, 0xc0003c04e0, 0xc0003c0570, 0x0, 0xc0003c0660, 0x13e3414, ...)
        /src/controller-https.go:123 +0xfa1
main.(*HAProxyController).handleTLSSecret(0xc00000be00, 0xc0004ffc00, 0x12, 0xc0004ffbe0, 0x1a, 0xc0003c04e0, 0xc0003c0570, 0x0, 0xc0003c0660, 0x13e3414, ...)
        /src/controller-https.go:195 +0x4f7
main.(*HAProxyController).updateHAProxy(0xc00000be00, 0x0, 0x0)
        /src/controller-haproxy.go:98 +0xf54
main.(*HAProxyController).SyncData(0xc00000be00, 0xc00023bda0, 0xc000088ea0)
        /src/controller-monitor.go:119 +0x42e
created by main.(*HAProxyController).monitorChanges
        /src/controller-monitor.go:26 +0xb9
```

Update:

I think the issue appear when an ingress use TLS secret with empty tls.crt or tls.key

**Comment by Mo3m3n** [comment]
Hi 
Thanks for reporting this bug.
I have fixed it here https://github.com/Mo3m3n/kubernetes-ingress/commit/b09f32ca3db4d1f0b4670023e1461114da3ab9e6 but I was not able to test it yet because I was not able to create a secret with an empty key:

    $ kubectl create secret tls test-empty-key  --key /tmp/key --cert /tmp/crt
    error: failed to load key pair tls: failed to find any PEM data in key input

Fix is available at `haproxytech/kubernetes-ingress:dev` image if you can give it a try

**Comment by Mo3m3n** [comment]
Fixed on master https://github.com/haproxytech/kubernetes-ingress/commit/df798c6f5d911d2c5c58264dda6eb20792ea6e46
