### ISSUE TITLE
Watch breaks on bad Ingress definition

### ISSUE THREAD

**Issue by morsik** [haproxytech/kubernetes-ingress#188]
Hi,

our devs reported us that they have problem adding new Ingresses. I checked ingress-controller logs and it throwed this error:

```
morsik@localhost ~ $ kubectl logs -n haproxy-controller  haproxy-ingress-7d76995f66-8qvl4
2020/05/07 12:35:05 
 _   _    _    ____                                            
| | | |  / \  |  _ \ _ __ _____  ___   _                       
| |_| | / _ \ | |_) | '__/ _ \ \/ / | | |                      
|  _  |/ ___ \|  __/| | | (_) >  <| |_| |                      
|_| |_/_/   \_\_|   |_|  \___/_/\_\\__, |                      
 _  __     _                       |___/             ___ ____  
| |/ /   _| |__   ___ _ __ _ __   ___| |_ ___  ___  |_ _/ ___| 
| ' / | | | '_ \ / _ \ '__| '_ \ / _ \ __/ _ \/ __|  | | |      
| . \ |_| | |_) |  __/ |  | | | |  __/ ||  __/\__ \  | | |___ 
|_|\_\__,_|_.__/ \___|_|  |_| |_|\___|\__\___||___/ |___\____| 
															 

2020/05/07 12:35:05 HAProxy Ingress Controller v1.4.3 f7e5401

2020/05/07 12:35:05 Build from: git@github.com:haproxytech/kubernetes-ingress.git
2020/05/07 12:35:05 Build date: 2020-04-14T15:37:47

2020/05/07 12:35:05 ConfigMap: haproxy-controller/haproxy
2020/05/07 12:35:05 Ingress class: 
2020/05/07 12:35:05 Publish service: 
2020/05/07 12:35:05 Default backend service: haproxy-controller/ingress-default-backend
2020/05/07 12:35:05 Default ssl certificate: haproxy-controller/
2020/05/07 12:35:05 Running with  HA-Proxy version 2.0.14 2020/04/02 - https://haproxy.org/
2020/05/07 12:35:05 Starting HAProxy with /etc/haproxy/haproxy.cfg
2020/05/07 12:35:05 Running on haproxy-ingress-7d76995f66-8qvl4
[WARNING] 127/123505 (18) : Can't open server state file '/var/state/haproxy/global': No such file or directory
2020/05/07 12:35:05 Running on Kubernetes version: v1.16.6 linux/amd64
E0507 12:35:05.926354       6 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 16 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x125db80, 0x1e600b0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/runtime/runtime.go:51 +0x82
panic(0x125db80, 0x1e600b0)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/haproxytech/kubernetes-ingress/controller.ConvertIngressRules(0xc000637020, 0x2, 0x2, 0x0)
	/src/controller/types.go:152 +0x302
github.com/haproxytech/kubernetes-ingress/controller.(*K8s).EventsIngresses.func1(0x13a62a0, 0xc00063c170)
	/src/controller/kubernetes.go:275 +0xc8
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:195
k8s.io/client-go/tools/cache.newInformer.func1(0x1272920, 0xc000367d80, 0x1, 0xc000367d80)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:367 +0x18a
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000202b00, 0xc000438750, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/delta_fifo.go:436 +0x235
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc00037b580)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:150 +0x40
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00054ef80)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00054ef80, 0x3b9aca00, 0x0, 0xc000160601, 0xc00009eae0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*controller).Run(0xc00037b580, 0xc00009eae0)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:124 +0x2c1
created by github.com/haproxytech/kubernetes-ingress/controller.(*K8s).EventsIngresses
	/src/controller/kubernetes.go:334 +0x291
[NOTICE] 127/123505 (20) : New worker #1 (21) forked
2020/05/07 12:35:11 Confiugring default_backend ingress-default-backend from ingress DefaultService
2020/05/07 12:35:11 HAProxy reloaded
```

after some investigation it turned out that this error was raised by broken `Ingress` definition which contained some strange line:

```
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: myapp
  namespace: some-devs-team
  annotations:
    haproxy.com/path-rewrite: /
spec:
  rules:
    - {}    # <----- THIS LINE CORRUPTED EVERYTHING; removing it causes haproxy-controller to work properly
    - host: www.domain.tld
      http:
        paths:
          - path: /event1
            backend:
              serviceName: test-real-time-1-2
              servicePort: 3000
```

Please check for this bug

**Comment by oktalz** [comment]
Hi @morsik , 

thx for the report.
This is confirmed and fixed with latest commit 3c07bf3

Now instead of crash controller log a warning about it
