### ISSUE TITLE
1.7 panic when running on k8s lower than 1.18

### ISSUE THREAD

**Issue by flabatut** [haproxytech/kubernetes-ingress#392]
# Summary

* Running fresh kubernetes cluster `v1.17.16`, no ingress resources installed
* Trying to run kubernetes-ingress `1.7.1` using [helm chart](https://github.com/haproxytech/helm-charts/tree/kubernetes-ingress-1.17.5/kubernetes-ingress)
* Pods are in running state after install
* As soon as ingress resource added, kubernetes-ingress pods panic and restart constantly.

# How to reproduce the issue

1. Install cluster
```
minikube start --kubernetes-version=v1.17.16
```
2. install haproxy
```
helm repo add haproxytech https://haproxytech.github.io/helm-charts
helm repo update
helm install my-release haproxytech/kubernetes-ingress
```
3. wait for haproxy running
```
minikube kubectl --  wait  pod -l'app.kubernetes.io/name=kubernetes-ingress' --for=condition=Ready --timeout=-120s
```
4. get logs in background
```
minikube kubectl --  logs -l'app.kubernetes.io/name=kubernetes-ingress' -f & 
```
5. create ingress resource
```
cat <<EOF | minikube kubectl -- apply -f -
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: default
  annotations:
    ingress.class: "haproxy"
spec:
  rules:
  - host: webdemo.com
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 80
EOF
```

6. Instantly after ingress addition the following logs should appear in console:

```
 _   _    _    ____                                            
| | | |  / \  |  _ \ _ __ _____  ___   _                       
| |_| | / _ \ | |_) | '__/ _ \ \/ / | | |                      
|  _  |/ ___ \|  __/| | | (_) >  <| |_| |                      
|_| |_/_/   \_\_|   |_|  \___/_/\_\\__, |                      
 _  __     _                       |___/             ___ ____  
| |/ /   _| |__   ___ _ __ _ __   ___| |_ ___  ___  |_ _/ ___| 
| ' / | | | '_ \ / _ \ '__| '_ \ / _ \ __/ _ \/ __|  | | |      
| . \ |_| | |_) |  __/ |  | | | |  __/ ||  __/\__ \  | | |___ 
|_|\_\__,_|_.__/ \___|_|  |_| |_|\___|\__\___||___/ |___\____| 
                               

2021/11/10 03:55:39 HAProxy Ingress Controller v1.7.1 04bbbc0
2021/11/10 03:55:39 Build from: https://github.com/haproxytech/kubernetes-ingress
2021/11/10 03:55:39 Build date: 2021-11-05T11:02:16

2021/11/10 03:55:39 ConfigMap: default/my-release-kubernetes-ingress
2021/11/10 03:55:39 Ingress class: haproxy
2021/11/10 03:55:39 Empty Ingress class: false
2021/11/10 03:55:39 Publish service: default/my-release-kubernetes-ingress
2021/11/10 03:55:39 Default backend service: default/my-release-kubernetes-ingress-default-backend
2021/11/10 03:55:39 Default ssl certificate: default/my-release-kubernetes-ingress-default-cert
2021/11/10 03:55:39 Frontend HTTP listening on: 0.0.0.0:80
2021/11/10 03:55:39 Frontend HTTPS listening on: 0.0.0.0:443
2021/11/10 03:55:39 Controller sync period: 5s

2021/11/10 03:55:39 Running on my-release-kubernetes-ingress-6564b8d795-c8bc4
2021/11/10 03:55:39 haproxy.go:36 Running with HAProxy version 2.4.8-d1f8d41 2021/11/03 - https://haproxy.org/
2021/11/10 03:55:39 haproxy.go:50 Starting HAProxy with /etc/haproxy/haproxy.cfg 
2021/11/10 03:55:39 haproxy.go:36 Running with HAProxy version 2.4.8-d1f8d41 2021/11/03 - https://haproxy.org/
2021/11/10 03:55:39 haproxy.go:50 Starting HAProxy with /etc/haproxy/haproxy.cfg 
2021/11/10 03:55:39 controller.go:116 Running on Kubernetes version: v1.17.16 linux/amd64
2021/11/10 03:55:39 controller.go:116 Running on Kubernetes version: v1.17.16 linux/amd64
2021/11/10 03:55:39 INFO    crmanager.go:75 Global CR defined in API core.haproxy.org
2021/11/10 03:55:39 INFO    crmanager.go:75 Global CR defined in API core.haproxy.org
2021/11/10 03:55:39 INFO    crmanager.go:75 Defaults CR defined in API core.haproxy.org
2021/11/10 03:55:39 INFO    crmanager.go:75 Backend CR defined in API core.haproxy.org
2021/11/10 03:55:39 INFO    crmanager.go:75 Defaults CR defined in API core.haproxy.org
2021/11/10 03:55:39 INFO    crmanager.go:75 Backend CR defined in API core.haproxy.org
E1110 03:55:39.558650    6076 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 102 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x17bd680, 0x292e520})
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/runtime/runtime.go:74 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x2000})
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/runtime/runtime.go:48 +0x75
panic({0x17bd680, 0x292e520})
E1110 03:55:39.569894    6052 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
  /usr/local/go/src/runtime/panic.go:1038 +0x215
goroutine 152 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x17bd680, 0x292e520})
github.com/haproxytech/kubernetes-ingress/controller/store.ingressNetworkingV1Beta1Strategy.ConvertIngress.func1({0xc00086a480, 0x0}, {0xc00083f6b0, 0x1, 0x1f4})
  /src/controller/store/convert.go:108 +0x459
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/runtime/runtime.go:74 +0x85
github.com/haproxytech/kubernetes-ingress/controller/store.ingressNetworkingV1Beta1Strategy.ConvertIngress({0xc00086a480, 0x0})
  /src/controller/store/convert.go:129 +0xd5
github.com/haproxytech/kubernetes-ingress/controller/store.ConvertToIngress({0x19c6200, 0xc00086a480})
  /src/controller/store/convert.go:42 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xfffffffe})
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/runtime/runtime.go:48 +0x75
panic({0x17bd680, 0x292e520})
github.com/haproxytech/kubernetes-ingress/controller.(*K8s).EventsIngresses.func1({0x19c6200, 0xc00086a480})
  /src/controller/kubernetes.go:412 +0x52
  /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/haproxytech/kubernetes-ingress/controller/store.ingressNetworkingV1Beta1Strategy.ConvertIngress.func1({0xc00021db00, 0x0}, {0xc0003dc0c0, 0x1, 0x0})
  /src/controller/store/convert.go:108 +0x459
github.com/haproxytech/kubernetes-ingress/controller/store.ingressNetworkingV1Beta1Strategy.ConvertIngress({0xc00021db00, 0x0})
  /src/controller/store/convert.go:129 +0xd5
github.com/haproxytech/kubernetes-ingress/controller/store.ConvertToIngress({0x19c6200, 0xc00021db00})
  /src/controller/store/convert.go:42 +0x85
github.com/haproxytech/kubernetes-ingress/controller.(*K8s).EventsIngresses.func1({0x19c6200, 0xc00021db00})
  /src/controller/kubernetes.go:412 +0x52
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
  /go/pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
  /go/pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/shared_informer.go:777 +0x9f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fba2d362fe0)
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4683e7, {0x1bf78e0, 0xc000b0b830}, 0x1, 0xc000a5e7e0)
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0xc0008a0fb0)
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc00087e100)
  /go/pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/shared_informer.go:771 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:73 +0x5a
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
  /go/pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/controller.go:231
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
  /go/pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/shared_informer.go:777 +0x9f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f8a8565b190)
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00012b738, {0x1bf78e0, 0xc0006cec60}, 0x1, 0xc0006b09c0)
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00012b7a0, 0x3b9aca00, 0x0, 0x0, 0xc00012b7b0)
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:133 +0x89
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:71 +0x88
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
  panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcbc499]

goroutine 152 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xfffffffe})
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/runtime/runtime.go:55 +0xd8
k8s.io/apimachinery/pkg/util/wait.Until(...)
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:90
panic({0x17bd680, 0x292e520})
  /usr/local/go/src/runtime/panic.go:1038 +0x215
k8s.io/client-go/tools/cache.(*processorListener).run(0xc00061cb00)
github.com/haproxytech/kubernetes-ingress/controller/store.ingressNetworkingV1Beta1Strategy.ConvertIngress.func1({0xc00021db00, 0x0}, {0xc0003dc0c0, 0x1, 0x0})
  /src/controller/store/convert.go:108 +0x459
github.com/haproxytech/kubernetes-ingress/controller/store.ingressNetworkingV1Beta1Strategy.ConvertIngress({0xc00021db00, 0x0})
  /src/controller/store/convert.go:129 +0xd5
github.com/haproxytech/kubernetes-ingress/controller/store.ConvertToIngress({0x19c6200, 0xc00021db00})
  /src/controller/store/convert.go:42 +0x85
github.com/haproxytech/kubernetes-ingress/controller.(*K8s).EventsIngresses.func1({0x19c6200, 0xc00021db00})
  /src/controller/kubernetes.go:412 +0x52
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
  /go/pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
  /go/pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/shared_informer.go:777 +0x9f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fba2d362fe0)
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4683e7, {0x1bf78e0, 0xc000b0b830}, 0x1, 0xc000a5e7e0)
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0xc0008a0fb0)
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc00087e100)
  /go/pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/shared_informer.go:771 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:73 +0x5a
  /go/pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/shared_informer.go:771 +0x6b
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:71 +0x88
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:71 +0x88
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
  panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcbc499]

goroutine 102 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x2000})
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x17bd680, 0x292e520})
  /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/haproxytech/kubernetes-ingress/controller/store.ingressNetworkingV1Beta1Strategy.ConvertIngress.func1({0xc00086a480, 0x0}, {0xc00083f6b0, 0x1, 0x1f4})
  /src/controller/store/convert.go:108 +0x459
github.com/haproxytech/kubernetes-ingress/controller/store.ingressNetworkingV1Beta1Strategy.ConvertIngress({0xc00086a480, 0x0})
  /src/controller/store/convert.go:129 +0xd5
github.com/haproxytech/kubernetes-ingress/controller/store.ConvertToIngress({0x19c6200, 0xc00086a480})
  /src/controller/store/convert.go:42 +0x85
github.com/haproxytech/kubernetes-ingress/controller.(*K8s).EventsIngresses.func1({0x19c6200, 0xc00086a480})
  /src/controller/kubernetes.go:412 +0x52
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
  /go/pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
  /go/pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/shared_informer.go:777 +0x9f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f8a8565b190)
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00012b738, {0x1bf78e0, 0xc0006cec60}, 0x1, 0xc0006b09c0)
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00012b7a0, 0x3b9aca00, 0x0, 0x0, 0xc00012b7b0)
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc00061cb00)
  /go/pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/shared_informer.go:771 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
  /go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:71 +0x88

```

# Comments

* Ingress resource is correctly registered:
```
minikube kubectl -- get ing -A
NAMESPACE   NAME          HOSTS         ADDRESS   PORTS   AGE
default     web-ingress   webdemo.com             80      8m15s

```
* minikube api-resource doesn't display appropriate group version but be declared v1beta1 
```
❯ minikube kubectl -- api-resources | grep -i ingress
ingresses                         ing          extensions                     true         Ingress
ingresses                         ing          networking.k8s.io              true         Ingress
```
* As soon as ingress resource deleted, haproxy no longer segfaults
* using `extensions` group gives the same result
* looking for https://github.com/haproxytech/kubernetes-ingress/blob/04bbbc03e3f3147243f20f62528a66021089d3ec/controller/store/convert.go#L108, `pathtype` attribute seems required but avail starting 1.18 only (https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/):
```
minikube kubectl -- explain ingress.spec.rules.http.paths.pathtype --api-version=networking.k8s.io/v1beta1
error: field "pathtype" does not exist
```
* Cannot reproduce the problem with `v1.18`. Running the same commands above, changing kubernetes version:
```
minikube start --kubernetes-version=v1.18.0
```
then adding ingress resource does no longer haproxy panic, only returning those expected log entries:
```
2021/11/10 04:15:07 ERROR   ingress/ingress.go:241 Ingress 'default/web-ingress': service 'default/web' does not exist
2021/11/10 04:15:09 ERROR   ingress/ingress.go:241 Ingress 'default/web-ingress': service 'default/web' does not exist
```

**Comment by Mo3m3n** [comment]
Thanks for reporting this
Fixed in next minor release `1.7.2`

**Comment by flabatut** [comment]
@Mo3m3n after attempted to deploy chart [1.17.10](https://github.com/haproxytech/helm-charts/tree/kubernetes-ingress-1.17.10/kubernetes-ingress) tied with kubernetes-ingress controller [1.7.2](https://github.com/haproxytech/helm-charts/blob/930b099d850019c4c5ec9a7079bdcaa3f20ddbaa/kubernetes-ingress/Chart.yaml#L20):

* the good thing is controller is running as expected
* the Bad thing is all ingresses are ignored, caused by undetected endpoints. The following log entries are returned:

```
2021/11/17 10:39:28 DEBUG   service/service.go:130 Service 'ingress-haproxy/kubernetes-ingress-default-backend': new backend 'ingress-haproxy-kubernetes-ingress-default-backend-http', reload required
2021/11/17 10:39:28 WARNING service/endpoints.go:33 Ingress 'ingress-haproxy/kubernetes-ingress-default-backend': no available endpoints
```

* Related deploy/services/endpoints are configured though:

```
kubectl get svc -n ingress-haproxy kubernetes-ingress-default-backend -o wide --show-labels
NAME                                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE    SELECTOR                                                                                                  LABELS
kubernetes-ingress-default-backend   ClusterIP   None         <none>        8080/TCP   7d5h   app.kubernetes.io/instance=kubernetes-ingress,app.kubernetes.io/name=kubernetes-ingress-default-backend   app.kubernetes.io/instance=kubernetes-ingress,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=kubernetes-ingress,app.kubernetes.io/version=1.7.2,helm.sh/chart=kubernetes-ingress-1.17.10
```

```
kubectl get endpoints -n ingress-haproxy --show-labels -o wide
NAME                                 ENDPOINTS                               AGE    LABELS
kubernetes-ingress-default-backend   172.24.129.40:8080,172.24.133.39:8080   7d5h   app.kubernetes.io/instance=kubernetes-ingress,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=kubernetes-ingress,app.kubernetes.io/version=1.7.2,helm.sh/chart=kubernetes-ingress-1.17.10,service.kubernetes.io/headless=
```

```
kubectl get deploy -n ingress-haproxy kubernetes-ingress-default-backend -o wide --show-labels
NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE    CONTAINERS                           IMAGES                                SELECTOR                                                                                                  LABELS
kubernetes-ingress-default-backend   2/2     2            2           7d5h   kubernetes-ingress-default-backend   k8s.gcr.io/defaultbackend-amd64:1.5   app.kubernetes.io/instance=kubernetes-ingress,app.kubernetes.io/name=kubernetes-ingress-default-backend   app.kubernetes.io/instance=kubernetes-ingress,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=kubernetes-ingress,app.kubernetes.io/version=1.7.2,helm.sh/chart=kubernetes-ingress-1.17.10

```

Should I create a new issue ?

**Comment by Mo3m3n** [comment]
@flabatut this looks like an IngressClass filtering issue.
And we did update this part both in Helm and Ingress Controller.
It is better to open a new dedicated issue. You will need to provide the following:
- k8s version you are using
- the controller args you are using (you can find that in `kubectl describe pod` )
- An example of an ingress resource that is ignored (you can provide the describe output or the manifest file)
Thanks !
