### ISSUE TITLE
Ingress container is backing off with the error Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)

### ISSUE THREAD

**Issue by kramakrishna-hue** [haproxytech/kubernetes-ingress#408]
Kubernetes Version: v1.12.5
Image used: haproxytech/kubernetes-ingress:1.7.0

2021/12/22 18:59:04 Running on nova-ingress-5dd6ddc55c-dwjbs
2021/12/22 18:59:05 haproxy.go:35 Running with HAProxy version 2.4.9-f8dcd9f 2021/11/24 - https://haproxy.org/
2021/12/22 18:59:05 haproxy.go:44 Starting HAProxy with /etc/haproxy/haproxy.cfg
2021/12/22 18:59:05 controller.go:117 Running on Kubernetes version: v1.12.5 linux/amd64
E1222 18:59:05.134550     214 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 193 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1756cc0, 0x286ff30})
	/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/runtime/runtime.go:74 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x18fd180})
	/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/runtime/runtime.go:48 +0x75
panic({0x1756cc0, 0x286ff30})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/haproxytech/kubernetes-ingress/controller/store.ingressExtensionsStrategy.ConvertIngress.func1({0xc000795470, 0x1, 0x452fb9})
	/src/controller/store/convert.go:204 +0x41f
github.com/haproxytech/kubernetes-ingress/controller/store.ingressExtensionsStrategy.ConvertIngress({0x451957})
	/src/controller/store/convert.go:224 +0x7a
github.com/haproxytech/kubernetes-ingress/controller/store.ConvertToIngress({0x1953740, 0xc000dae180})
	/src/controller/store/convert.go:51 +0xe5
github.com/haproxytech/kubernetes-ingress/controller.(*K8s).EventsIngresses.func1({0x1953740, 0xc000dae180})
	/src/controller/kubernetes.go:412 +0x52
k8s.io/client-go/tools/cache.ResourceEventHandl
[logs-from-nova-ingress-in-nova-ingress-5dd6ddc55c-dwjbs.txt](https://github.com/haproxytech/kubernetes-ingress/files/7764677/logs-from-nova-ingress-in-nova-ingress-5dd6ddc55c-dwjbs.txt)
erFuncs.OnAdd(...)
	/go/pkg/mod/k8s.io/client-go@v0.21.3/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/pkg/mod/k8s.io/client-go@v0.21.3/tools/cache/shared_informer.go:777 +0x9f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f382af7d7f0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0004f7738, {0x1b780c0, 0xc00065bc20}, 0x1, 0xc00092b020)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0004f77a0, 0x3b9aca00, 0x0, 0x0, 0xc0004f77b0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000560380)
	/go/pkg/mod/k8s.io/client-go@v0.21.3/tools/cache/shared_informer.go:771 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/wait/wait.go:71 +0x88
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcc489f]

**Comment by Mo3m3n** [comment]
Hi
Few bugs were fixed in 1.7 that may be related to this issue.
Can you please try with latest `1.7`: currently it is `1.7.3`  and try again.
