### ISSUE TITLE
SIGSEGV with 3.0.3 in service.go:148

### ISSUE THREAD

**Issue by EFX-PXT1** [haproxytech/kubernetes-ingress#683]
Hi,

Upgraded from 3.0.2 to 3.0.3 and observing a pod in CrashLoopBackoff

Startup Log 
```
[NOTICE]   (69) : haproxy version is 3.0.5-8e879a5
[WARNING]  (69) : config : frontend 'https' has no 'bind' directive. Please declare it as a backend if this was intended.
[WARNING]  (69) : config : frontend 'http' has no 'bind' directive. Please declare it as a backend if this was intended.
[WARNING]  (69) : config : frontend 'healthz' has no 'bind' directive. Please declare it as a backend if this was intended.
[WARNING]  (69) : config : frontend 'stats' has no 'bind' directive. Please declare it as a backend if this was intended.
[WARNING]  (69) : config : Removing incomplete section 'peers localinstance' (no peer named 'kubernetes-ingress-7ff46b49f6-28zfn').
2024/10/22 14:06:12 
 _   _    _    ____
| | | |  / \  |  _ \ _ __ _____  ___   _
| |_| | / _ \ | |_) | '__/ _ \ \/ / | | |
|  _  |/ ___ \|  __/| | | (_) >  <| |_| |
|_| |_/_/   \_\_|   |_|  \___/_/\_\\__, |
 _  __     _                       |___/             ___ ____
| |/ /   _| |__   ___ _ __ _ __   ___| |_ ___  ___  |_ _/ ___|
| ' / | | | '_ \ / _ \ '__| '_ \ / _ \ __/ _ \/ __|  | | |
| . \ |_| | |_) |  __/ |  | | | |  __/ ||  __/\__ \  | | |___
|_|\_\__,_|_.__/ \___|_|  |_| |_|\___|\__\___||___/ |___\____|


2024/10/22 14:06:12 HAProxy Ingress Controller v3.0.3 6164e149.dirty
2024/10/22 14:06:12 Build from: github.com/haproxytech/kubernetes-ingress
2024/10/22 14:06:12 Git commit date: 2024-10-02T14:53:51Z
2024/10/22 14:06:12 ConfigMap: haproxy-system/kubernetes-ingress
```

Logs prior to SEGV and termination
```
2024/10/22 14:06:18 INFO    service/service.go:168 [transactionID=be7dfdf2-b623-4a0f-91af-a1159b0fc8ed] reload required : Service 'sre-echo/echo-service': new backend 'sre-echo_echo-service_http-port'
2024/10/22 14:06:18 INFO    service/endpoints.go:160 [transactionID=be7dfdf2-b623-4a0f-91af-a1159b0fc8ed] reload required : [CONFIG] [BACKEND] [SERVER] Server slots in backend 'sre-echo_echo-service_http-port' scaled to match available endpoints
2024/10/22 14:06:18 INFO    service/service.go:168 [transactionID=be7dfdf2-b623-4a0f-91af-a1159b0fc8ed] reload required : Service 'xmllocate-qa/xmllocate-chart-acceptance': new backend 'xmllocate-qa_xmllocate-chart-acceptance_xmllocate'
2024/10/22 14:06:18 INFO    service/endpoints.go:160 [transactionID=be7dfdf2-b623-4a0f-91af-a1159b0fc8ed] reload required : [CONFIG] [BACKEND] [SERVER] Server slots in backend 'xmllocate-qa_xmllocate-chart-acceptance_xmllocate' scaled to match available endpoints
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1da4ea8]

goroutine 29 [running]:
github.com/haproxytech/kubernetes-ingress/pkg/service.(*Service).HandleBackend(0xc0062be690, {{0xc000341bc0, 0xc000341c40, 0xc000341cc0, 0xc000341d40}, {0xc000698210, 0xc000698240}, 0xc000698150, 0xc000698180, 0xc0062f6510, ...}, ...)
        /src/pkg/service/service.go:148 +0x88
github.com/haproxytech/kubernetes-ingress/pkg/ingress.(*Ingress).handlePath(_, {{0xc000341bc0, 0xc000341c40, 0xc000341cc0, 0xc000341d40}, {0xc000698210, 0xc000698240}, 0xc000698150, 0xc000698180, 0xc0062f6510, ...}, ...)
        /src/pkg/ingress/ingress.go:104 +0x15a
github.com/haproxytech/kubernetes-ingress/pkg/ingress.(*Ingress).Update(_, {{0xc000341bc0, 0xc000341c40, 0xc000341cc0, 0xc000341d40}, {0xc000698210, 0xc000698240}, 0xc000698150, 0xc000698180, 0xc0062f6510, ...}, ...)
        /src/pkg/ingress/ingress.go:245 +0xc36
github.com/haproxytech/kubernetes-ingress/pkg/controller.(*HAProxyController).updateHAProxy(0xc000737088)
        /src/pkg/controller/controller.go:157 +0x12a5
github.com/haproxytech/kubernetes-ingress/pkg/controller.(*HAProxyController).SyncData(0xc000737088)
        /src/pkg/controller/monitor.go:38 +0x558
github.com/haproxytech/kubernetes-ingress/pkg/controller.(*HAProxyController).Start(0xc000737088)
        /src/pkg/controller/controller.go:99 +0x217
created by main.main in goroutine 1
        /src/main.go:156 +0xde9
Ingress Controller exited with fatal code 2, taking down the S6 supervision tree
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service ingress-controller: stopping
s6-rc: info: service ingress-controller successfully stopped
s6-rc: info: service haproxy: stopping
[NOTICE]   (69) : haproxy version is 3.0.5-8e879a5
[WARNING]  (69) : Exiting Master process...
[WARNING]  (109) : Proxy https stopped (cumulated conns: FE: 0, BE: 0).
[WARNING]  (109) : Proxy http stopped (cumulated conns: FE: 0, BE: 0).
[WARNING]  (109) : Proxy healthz stopped (cumulated conns: FE: 0, BE: 0).
[WARNING]  (109) : Proxy stats stopped (cumulated conns: FE: 0, BE: 0).
[WARNING]  (69) : Current worker (109) exited with code 0 (Exit)
[WARNING]  (69) : All workers exited. Exiting... (0)
```

Appreciate any thoughts.

**Comment by ivanmatmati** [comment]
Hi @EFX-PXT1 , thanks for reporting. I've spotted why you get the fault. I'll send a fix. The origin of the error could be that you've got an ingress refering to a non existing port on the service. Please chek that.

**Comment by EFX-PXT1** [comment]
Thanks for the pointer @ivanmatmati 
Did indeed find a service without ports - once removed it stopped crashing.
Is there a link to the 'nightly' source code ?
Spotted L148 should probably drop below the err != nil
- https://github.com/haproxytech/kubernetes-ingress/blob/v3.0.3/pkg/service/service.go#L148

Best Regards

**Comment by ivanmatmati** [comment]
Yes, indeed, this is the cause.

**Comment by EFX-PXT1** [comment]
Yep - found fixed on master - appreciate it - have a great day
